name: Destruction de l'infrastructure - Terraform

on:
    workflow_dispatch:

permissions:
    id-token: write
    contents: read


jobs:
    destroy-infra:
        runs-on: ubuntu-latest
        steps:
            - name: Récupération du code source
              uses: actions/checkout@v4
            
            - name: Connexion à AWS via OIDC
              uses: aws-actions/configure-aws-credentials@v4
              with:
                role-to-assume: ${{ secrets.AWS_ROLE }}
                aws-region: ${{ secrets.AWS_REGION }}
            
            - name: Setup Terraform environnement
              uses: hashicorp/setup-terraform@v3

            - name: terraform initialisation
              working-directory: infrastructure
              run: terraform init

            - name: destruction l'infrastructure
              working-directory: infrastructure
              run: terraform destroy -auto-approve